### ISSUE TITLE
[OpenAI API][TB128+] No response - seems like no prompt is sent

### ISSUE THREAD

**Issue by morgggg** [micz/ThunderAI#107]
Window opens when AI action is selected on any mail and only following is shown for any prompt through API (web interface works):
Information
Will attempt to connect to OpenAI ChatGPT using the API key provided...

Get answers for follow up prompts in the window. No error.

![image](https://github.com/user-attachments/assets/984de045-2ba1-43fc-bfaa-fd086627662c)

**Comment by micz** [comment]
Are you using Thunderbird 115?
Which version of the addon are you using?
May you check the console error?
Thank you.

**Comment by morgggg** [comment]
No, forgot I am using beta - so 130.0b1 (64-bit).
2.0.2
1723729660580	addons.xpi	WARN	Checking C:\Program Files\Mozilla Thunderbird Beta\distribution\extensions for addons
1723729661189	addons.xpi	WARN	Addon with ID thunderbird-compact-light@mozilla.org already installed, older version will be disabled
1723729661189	addons.xpi	WARN	Addon with ID thunderbird-compact-dark@mozilla.org already installed, older version will be disabled
browser is null [ext-tabs.js:76:1](chrome://messenger/content/parent/ext-tabs.js)
Uncaught (in promise) Error: An unexpected error occurred undefined
sizeToContent() is deprecated and will be removed in the future. 2 [commonDialog.js:135:10](chrome://global/content/commonDialog.js)
[ThunderAI] Prompt length: 1129 [mzta-background.js:143:13](moz-extension://416a7903-b8df-4b76-92b7-1be93d190f6b/mzta-background.js)
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
[index.html](moz-extension://416a7903-b8df-4b76-92b7-1be93d190f6b/api_webchat/index.html)
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    openChatGPT moz-extension://416a7903-b8df-4b76-92b7-1be93d190f6b/mzta-background.js:249
[mzta-background.js:249:22](moz-extension://416a7903-b8df-4b76-92b7-1be93d190f6b/mzta-background.js)
[ThunderAI] appendUserMessage: Will attempt to connect to OpenAI ChatGPT using the API key provided... [messagesArea.js:139:17](moz-extension://416a7903-b8df-4b76-92b7-1be93d190f6b/api_webchat/messagesArea.js)

**Comment by micz** [comment]
Ok, I think I got the problem. Thank you.

**Comment by morgggg** [comment]
No problem. Thank you! Awesome add on.

**Comment by micz** [comment]
To be released in version 2.0.3.
Wating for the editor review on the addon site, you can download it here: https://github.com/micz/ThunderAI/releases/tag/v2.0.3
