### ISSUE TITLE
[OpenAI API] Scrollbar missing in ThunderAI window

### ISSUE THREAD

**Issue by morgggg** [micz/ThunderAI#108]
**Thunderbird version and OS**
TB 130.0b1 Win11

**ThunderAI version**
2.0.3

**Describe the bug**
Scrollbar missing in ThunderAI window when using API integration.

**To Reproduce**
1. Use a prompt to generate a long response when using API integration.
2. Window does not show scrollbar - you can not scroll through response that is too long to fit in the window.

**Expected behavior**
There should be scrollbar if text does not fit window.

**Comment by micz** [comment]
To be released in version 2.0.4.
Wating for the editor review on the addon site, you can download it here: https://github.com/micz/ThunderAI/releases/tag/v2.0.4

Thank you for your report.
