### ISSUE TITLE
Manage custom prompts 

### ISSUE THREAD

**Issue by micz** [micz/ThunderAI#12]
Add the ability to manage custom prompts and disable a single one, even a default one. 

Still to do:
- [x] Implement the item edit button function
- [x] Implement the item delete button function
- [x] Add messaging in saving the prompts
- [x] Check css for light mode
- [x] Improve design for the new item form
- [x] The new btn must be disabled when the form is opened.
- [x] Edit "action" property in listjs with the select
- [x] Edit "type" property in listjs with the select
- [x] i18n all strings
- [x] Fix "Unknown localization message" error for custom prompts

**Comment by AI4everr** [comment]
As written in the review:

Instant Reply Integration: Thunderbird AI swiftly inserts replies into email windows, bypassing manual steps.
Your response:

Instant Reply Integration: To accomplish this, using the ChatGTP API is necessary, but it is a pay-per-use service.
I couldn't find an email anywhere, so I'm replying here if that's okay.

A paid service is not an issue; I currently use ChatGPT's paid service as well. It would be great if I could input my API key into your software to respond directly in the email window.

**Comment by micz** [comment]
@AI4everr I moved you message in #40 as a new feature.
I'm going to hide these comments.

**Comment by AI4everr** [comment]
Thank you micz, awesome! 👍

**Comment by micz** [comment]
To be released in version 1.1.

**Comment by micz** [comment]
This feature can be tested in the new prelease version: https://github.com/micz/ThunderAI/releases/tag/v1.1.0pre1
