### ISSUE TITLE
[ChatGPT Web] ThunderAI won't send prompts to Chatgpt window when the page loads slowly

### ISSUE THREAD

**Issue by jamaical82** [micz/ThunderAI#122]
**Thunderbird version and OS**
Thunderbird 115.14.0 - Windows 10 

**ThunderAI version**
ThunderAI 2.1.1

**Describe the bug**
Since Saturday, when I use Thunderbird to reply, the ChatGPT window opens but nothing happens. I have the same problem on all my computers.

**Screenshots**
Attachement

Thank you for your amazing work!

![error](https://github.com/user-attachments/assets/4128819e-33fa-4ba7-8fd2-79fbe8438213)

**Comment by micz** [comment]
I tried it and it works as usual, so it should not be a change in the ChatGPT web interface.
May you post here the log from the Thunderbird Console?
When there is a blank page like the one you get, usually it's something abount the webpage not loading correctly (like a 401 error).

**Comment by jamaical82** [comment]
thank you for reply, here a screenshot of Thunderbird Console
![error](https://github.com/user-attachments/assets/b65d6fae-f1cf-49cd-9bfa-5241676c7092)

**Comment by micz** [comment]
Searching online it seems an error due to a change in the html before rendering: https://react.dev/errors/418

In a post I found on stackoverflos it seems could be related to a browser extension: https://stackoverflow.com/a/76046970

ThunderAI does nothing before the ChatGPT page loads, do you have installed a new extension the day you started to see this behaviour?

**Comment by jamaical82** [comment]
No, I didn’t make any changes since last Saturday when ThunderAI stopped working. One thing I noticed is that if I use my laptop at home, ThunderAI works as expected. However, if I use it at work, ThunderAI gives me that problem. In both cases, the Wi-Fi connection is direct to the router, without firewalls or anything like that. When I’m at work and I use a VPN to connect to my home network, ThunderAI works. Until last Saturday, everything worked like a charm.

**Comment by micz** [comment]
Maybe at work there is something that is filtering the ChatGPT page?
If you open it in a browser from work does it load correctly?

**Comment by jamaical82** [comment]
I can use ChatGPT without any problems from the browser and also from Thunderbird (after the error screen, ChatGPT opens normally even though the prompts from ThunderAI are not transmitted). It’s very strange, it seems to have something to do with the ISP, as at work I have a static IP while at home I have a dynamic IP. Additionally, the router is configured simply, without filters or blocks. I tried using various DNS settings, but without success.

**Comment by micz** [comment]
> also from Thunderbird (after the error screen, ChatGPT opens normally even though the prompts from ThunderAI are not transmitted)

Maybe it loads slowly after reporting the errors in the log you posted? So ThunderAI thinks it's not loading because it's taking too much time?

**Comment by jamaical82** [comment]
Can be the problem, is there a way to say to ThunderAI to wait a little bit more before sending prompts to chatgpt? Anyway this not explain why if I use a VPN to home it works, but if it's possible I will test this.

**Comment by micz** [comment]
I'll add a button to retry the action in case of an error, so you could click it after the page is fully loaded.

I'll make a prerelease to test it and update this issue.

**Comment by micz** [comment]
@jamaical82 may you try this pre release?

https://github.com/micz/ThunderAI/releases/tag/v2.1.2pre1

Thank you.

**Comment by jamaical82** [comment]
I’ll test it tomorrow at work where I can reproduce the bug. Thank you for your support.

**Comment by jamaical82** [comment]
I tested the pre-release, but unfortunately, it doesn't work in my case. The screen with the error (and the new button) appears for a fraction of a second, then disappears and continues on ChatGPT without sending the prompt. I tried clicking the retry button quickly, but nothing happens. I cleared the cache, disconnected the account (login via Google), uninstalled and reinstalled ThunderAI. I also tried a clean installation of Thunderbird on another PC, but the problem persists. There are no other plugins installed; the issue seems to stem from some conflict with my ISP. There are no filters, rules, or blocks in the router, and I tried using different DNS servers (Google, Cloudflare). Is there anything I can do to provide you with more details?

**Comment by micz** [comment]
May you make a video?
You can send it to m@micz.it.

**Comment by jamaical82** [comment]
Sent

**Comment by micz** [comment]
Ok, I got it, thanks.
Iì'll work on it and post here again.

**Comment by micz** [comment]
This release should fix it: https://github.com/micz/ThunderAI/releases/tag/v2.1.2pre2

May you test it?
Thanks.

**Comment by jamaical82** [comment]
Now it works perfectly, thank you for the amazing work!

**Comment by micz** [comment]
Released in version 2.1.2.
