### ISSUE TITLE
Update Ollama Model List

### ISSUE THREAD

**Issue by j2318** [micz/ThunderAI#124]
**Thunderbird version and OS**
128.1.1esr (64-bit) macOS Sonoma 14.6.1

**ThunderAI version**
2.1.1
**AI Integration**
- [ ] ChatGPT Web Interface
- [ ] OpenAI ChatGPT API
- [ X] Ollama API

**Describe the bug**
When Update Ollama Models list I am getting 
The page at ThunderAI says:
Error trying to fetch Ollama models: NetworkError when attempting to fetch resource.

Ollama is running http://127.0.0.1:11434

I setup 
`launchctl setenv OLLAMA_ORIGINS moz-extension://*`

I have following models installed:

NAME          	ID          	SIZE  	MODIFIED
mistral:latest	f974a74358d6	4.1 GB	About an hour ago
llama2:latest 	78e26419b446	3.8 GB	2 hours ago

**Comment by micz** [comment]
May you post here the Thunderbird console log?

**Comment by j2318** [comment]
06:48:14.203 XHROPTIONS
http://127.0.0.1:11434/api/tags
CORS Missing Allow Origin

06:48:14.208 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:11434/api/tags. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 403.
06:48:14.209 XHRGET
http://127.0.0.1:11434/api/tags
NS_ERROR_DOM_BAD_URI

	
GET
	http://127.0.0.1:11434/api/tags
Transferred0 GB (0 GB size)
Referrer Policystrict-origin-when-cross-origin
Request PriorityHighest
DNS ResolutionSystem

06:48:14.209 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:11434/api/tags. (Reason: CORS request did not succeed). Status code: (null).
06:48:14.209 [ThunderAI Logger | mzta-options] Error trying to fetch Ollama models mzta-logger.js:39:17
06:48:14.232 sizeToContent() is deprecated and will be removed in the future. commonDialog.js:132:10
06:50:21.343 ReferenceError: window is not defined 2 utils.js:56:34

**Comment by micz** [comment]
That is a CORS issue.
It seems it's not correctly settings the OLLAMA_ORIGINS.

**Comment by j2318** [comment]
Yes it looks like CORS problem.  What should I do?

**Comment by micz** [comment]
Try with the double quotes

`launchctl setenv OLLAMA_ORIGINS "moz-extension://*"`

**Comment by j2318** [comment]
I tried you last idea but no change, still CORS problem

**Comment by micz** [comment]
I don't have a Mac, but this is what I found:

https://medium.com/dcoderai/how-to-handle-cors-settings-in-ollama-a-comprehensive-guide-ee2a5a1beef0

Set the env var with launchctl and restart the application.
The problem you're experiencing is on the Ollama side.

**Comment by lakonis** [comment]
On Linux (Manjaro), I fixed the problem by adding those two lines l4-5 :

```
### Editing /etc/systemd/system/ollama.service.d/override.conf
### Anything between here and the comment below will become the contents of the drop-in file

[Service]
Environment="OLLAMA_ORIGINS=moz-extension://*"

### Edits below this comment will be discarded
[...]
```

**Comment by micz** [comment]
Thank you @lakonis for your contribution.
From my understanding every system has it's way to set this parameter.

**Comment by micz** [comment]
I've added an information page about Ollama CORS: https://micz.it/thunderbird-addon-thunderai/ollama-cors-information/
