### ISSUE TITLE
Support LM-Studio or generally an alternative/local OpenAI-compatible API

### ISSUE THREAD

**Issue by giantamoeba** [micz/ThunderAI#126]
**Is your feature request related to a problem? Please describe.**
I am still undecided between Ollama and LM-Studio, each has its pros and cons, however LM-Studio imitates the OpenAI-API; therefore it should be easy to support.

**Describe the solution you'd like**
An additional field in the ChatGPT OpenAI API for setting the ip and port, instead of hardcoding them. That would be enough to work with LM-Studio or any other alternative OpenAI-compatible API.

**Comment by micz** [comment]
I'll do some tests, thank you for your suggestion.

**Comment by micz** [comment]
I'll add it in a future release.
Thank you.

**Comment by giantamoeba** [comment]
Thank you for that, I'll be looking forward to it.

**Comment by micz** [comment]
@giantamoeba please, try the pre release version **2.2.0pre1** from here: https://github.com/micz/ThunderAI/releases

I've added a new "_OpenAI Comp API_" integration method.
Thank you.

**Comment by dguembel-itomig** [comment]
Hello! @micz I believe an "OpenAI Compatible" option should also permit to set an API key (=Bearer token), analogously to what stock "OpenAPI" permits/requires, but it seems that is not configurable at the moment. Could this be added? I'm happy to test (against Ollama / Open WebUI for example) if this helps.

**Comment by micz** [comment]
I could add it as an optional parameter, I've filed #144.
I'll get back to you on this issue.

**Comment by micz** [comment]
You can find here version 2.2.0_oai_comp_key_v1.

Please follow this steps:

1. Download the file [thunderai-v2.2.0_oai_comp_key_v1.zip](https://github.com/user-attachments/files/17216336/thunderai-v2.2.0_oai_comp_key_v1.zip)
2. Rename it from *.zip to *.xpi
3. Backup your custom prompts if you have any
4. Install this version

In this version, with the OpenAI Comp API, if an API key is present in the options, it will be used.
@dguembel-itomig let me know how it goes!

**Comment by micz** [comment]
May you tell me which Operative System and Thunderbird version are you using?
May you give me a link to download the local LLM you're using?

**Comment by dguembel-itomig** [comment]
I am on Ubuntu 24.04 LTS. Thunderbird is 128.2.3esr (64-Bit). I am running against an instance of Open-Webui (latest, = 0.3.30) with an Ollama (latest, = 0.3.12) underneath. The LLM I am running against is llama3.2, from here: https://ollama.com/library/llama3.2

Does that help, or do you need other information? Thank you again for all you efforts, I appreciate it!

**Comment by micz** [comment]
Does it happen all the time?

May you try this version?
[thunderai-v2.2.0_i145_v3.zip](https://github.com/user-attachments/files/17236193/thunderai-v2.2.0_i145_v3.zip)

It adds more logs and it should try to manage broken chunks. I'm not able to reproduce the problem, so may you post the logs also if it works? (I'm optimistic :sweat_smile:)
Thank you.

**Comment by dguembel-itomig** [comment]
Thank you for the fast answer and the new version (2.2.0! I've tried it out, and now it works. Please find attached the log file. If there's anything else I can do to help, please feel free to get back to me. Thank you again for your quick answer.

P.S. Yes, it happened all the time, I never got an answer back in the ThunderAI GUI. I was thinking about a problem on the olllama/webgui side, but If there's one, I do not see what it would have been, the responses looked correct. Do you have an Idea? 
[console-export-2024-10-3_8-37-17.txt](https://github.com/user-attachments/files/17240366/console-export-2024-10-3_8-37-17.txt)

**Comment by micz** [comment]
Thank you @dguembel-itomig for your feedback.
May you try this version?
I've added more logs. thank you.

[thunderai-v2.2.0_i145_v4.zip](https://github.com/user-attachments/files/17247661/thunderai-v2.2.0_i145_v4.zip)

Please, clear the console before using the addon, so you'll send only the related log. I deleted the attachment in the previous comment because it seems to contain sensitive information.

**Comment by dguembel-itomig** [comment]
Hello @micz thank you for being so vigilant. I looked for API keys in the logs (were not there) and missed the rest :-|

Re-tested (I cleared the log, took the github notification mail informing me of your previous comment, and asked the AI to summarize - waited for the result which does indeed come as desired, then exported log to file). Hope this helps you, please let me know if I can be of further assistance. 
[console-export-2024-10-3_19-22-50.txt](https://github.com/user-attachments/files/17247873/console-export-2024-10-3_19-22-50.txt)

**Comment by micz** [comment]
I'll add this code to version 2.2.0.
I'll ask you to test the final 2.2.0 pre-release to ensure everything works.
Thank you.

**Comment by micz** [comment]
I've released version 2.2.0pre5, may you test it?
See the changelog: https://github.com/micz/ThunderAI/releases/tag/v2.2.0pre5
Thank you.

**Comment by dguembel-itomig** [comment]
Installed and tried out - seems to be working very well so far. No hangs, all answers correctly received and displayed. Will let you know if I stumble across anything, but likely not before early next week. Thank you already!

**Comment by micz** [comment]
Available in version 2.2.0.

**Comment by giantamoeba** [comment]
I am trying with LM-Studio, obtaining the models does not seem to work, LM-Studio Console is showing:
```
[ERROR] 
Unexpected endpoint or method. (OPTIONS /v1/models). Returning 200 anyway
```
The method `OPTIONS` does not seem to be the correct one, since the endpoint expects a `GET /v1/models`, is it something special for LM-Studio?

If I insert the name of the model manually, I still get an error while inferencing, LM-Studio says:
```
[DEBUG] Received request: OPTIONS to /v1/models
[ERROR] 'messages' field is required```
Apparently LM-Studio again does not expect `OPTIONS`. Does this mean that LM-Studio is incomaptible with the Open-AI API?

**Comment by micz** [comment]
@giantamoeba thank you for adding the solution.
It's not the first time a CORS error reports an OPTION command that ThunderAI does not use anywhere.
