### ISSUE TITLE
2.1.1 Unable to Complete (and others)

### ISSUE THREAD

**Issue by twigandolive** [micz/ThunderAI#128]
### The problem

2.1.1 seemed to introduce some bugs. First, replies no longer auto-complete and require "force completion" every time. Clicking on the text no longer highlights it to use "selected response," so highlighting the full answer is required. Even this, it doesn't always paste in the message; instead, it just shows "ChatGPT" or a couple of return spaces. (This happens sporadically.) . Also, sometimes using "Reply to this" just opens the ChatGPT window with no action run, requiring the window to be closed before "Reply to this" works as intended. 

I've tried restarting TB, my computer, and relogging into ChatGPT. I use a 1200x1200 window, a default signature name (tried without), English as the default language, Reply to All, the ChatGPT web interface, and ChatGPT 4. 

### Which Operative System are you using?

MacOS X Sonoma 14.6.1

### Which version of Thunderbird are you using?

128.2.0esr

### Which version of ThunderAI has the issue?

2.1.1

### Which integration are you using?

ChatGPT Web Interface

**Comment by micz** [comment]
There were many changes in the ChatGPT web interface, please try version 2.1.2 from here https://github.com/micz/ThunderAI/releases/tag/v2.1.2

**Comment by micz** [comment]
The version is now available updating directly from Thunderbird.

**Comment by twigandolive** [comment]
I installed 2.1.3 this morning, and so far, everything is back to normal. Thanks!

**Comment by micz** [comment]
Great!
