### ISSUE TITLE
ThunderAI stuck on prompt screen

### ISSUE THREAD

**Issue by jamaical82** [micz/ThunderAI#133]
From this afternoon ThunderAI won't sent prompts with this error message. Button "retry" doesn't work

![thunderai error](https://github.com/user-attachments/assets/6303ab40-4e93-41ab-b390-136edf9b05ba)

### Which Operative System are you using?

windows 11

### Which version of Thunderbird are you using?

128.2.0esr

### Which version of ThunderAI has the issue?

2.1.3

### Which integration are you using?

ChatGPT Web Interface

### Additional information

![thunderai log error](https://github.com/user-attachments/assets/6063d9ad-ee07-4bec-a0bd-cdf8f3cb09d7)

**Comment by micz** [comment]
They changed again the web interface.
I'm working on it.

**Comment by micz** [comment]
Fixed in https://github.com/micz/ThunderAI/releases/tag/v2.1.4

Thank you for reporting this issue.

**Comment by jamaical82** [comment]
thank you Mic, amazing as always
