### ISSUE TITLE
fetch Ollama models: NetworkError

### ISSUE THREAD

**Issue by Sunightt** [micz/ThunderAI#136]
### The problem

Hello, I don't understand why but I can't connect to Ollama. The API is accessible, I've even tried with a local server but I get the same error. :

![image](https://github.com/user-attachments/assets/ee39bedf-d236-4a1f-8660-cd1831350a79)

### Which Operative System are you using?

Windows 11

### Which version of Thunderbird are you using?

Version 128.2.2esr (64 bits)

### Which version of ThunderAI has the issue?

2.1.4

### Which integration are you using?

Ollama API

**Comment by micz** [comment]
May you activate the debug, try again and post the log from Thunderbird?
Thank you.

**Comment by actXc** [comment]
I use win11 and I was able to solve the network error like this: 

1. Open Windows Settings (Windows key + I).
2. Search for "environment variables".
3. Click on "Edit the system environment variables".
4. In the new window, click "Environment Variables".
5. Under "System variables", click "New".
6. Variable name: OLLAMA_ORIGINS
7. Variable value: moz-extension://*
8. Confirm with "OK".
9. Restart your PC.

**Comment by micz** [comment]
Thank you @actXc for your help!
Correctly configuring CORS seems to be somewhat problematic, as it depends not only on the OS but also on how you run Ollama.

**Comment by jatoko** [comment]
On MacOs:

1. Open terminal
2. Run the following command in the terminal: launchctl setenv OLLAMA_ORIGINS "moz-extension://*"
3. (Re)start Ollama (e.g., quit, start)

**Comment by micz** [comment]
Thank you @jatoko for your contribution!
I'll add an info page with also all the details provided in this issue: #141.

**Comment by micz** [comment]
I've added an information page about Ollama CORS: https://micz.it/thunderbird-addon-thunderai/ollama-cors-information/
