### ISSUE TITLE
not respodning

### ISSUE THREAD

**Issue by michsanto** [micz/ThunderAI#138]
won't working

just not reaction 
just shown working in progress..

**Comment by micz** [comment]
In you are using Thunderbird 115, the problem is described here: https://github.com/micz/ThunderAI/issues/139

**Comment by micz** [comment]
If you're using Thunderbird 115, install version 2.1.5: https://github.com/micz/ThunderAI/releases/tag/v2.1.5

If the problem is not related to this, feel free to reopen the issue and provide more details about what you're experiencing.
