### ISSUE TITLE
Placeholders in Prompts

### ISSUE THREAD

**Issue by schucan** [micz/ThunderAI#146]
**Is your feature request related to a problem? Please describe.**

Currently, the "selected text" is just appended to the prompt.

There are two distinct situations where this is inconvenient:

1. Some prompts would be better if the selected text would be *inside* the prompt instead of at the end.
    - example: "This is a support request I received: %t /// Please write a polite answer with many more questions to discourage followups", where %t would be replaced by the selected text.
2. When the "Ask for additional text" option is used, it would be just as great to have the cursor placed in that exact location. 
    - example: "This is an email I received: %t /// Please write a polite and complete answer email expressing %c. Make it polite and funny.", where %t would be replaced by the selected text and the cursor would be blinking where the %c is.

**Describe the solution you'd like**

See above:
- `%t` would be replaced with selected text.
- cursor would be placed where `%c` is in prompt.

**Additional context**

This is somehow implemented in [AI Anywhere Add-On](https://addons.mozilla.org/de/firefox/addon/ai_anywhere/) (but it otherwise has a lot less features...).

**Comment by micz** [comment]
I've released version 2.3.0pre1, you can find it here: https://github.com/micz/ThunderAI/releases/tag/v2.3.0pre1
In this page is described how this feature works: https://micz.it/thunderbird-addon-thunderai/data-placeholders/

May you test it?
Remeber to backup your custom prompts if you have any.
Thank you!

**Comment by micz** [comment]
Released in version 2.3.0.
