### ISSUE TITLE
Window not opening using an Owl account

### ISSUE THREAD

**Issue by soufron** [micz/ThunderAI#148]
Hi, just installed it but when I am looking at a mail on my main mail account, and then click on the AI button, whether to resume it or whatever, no window appears. 

It works with my other mails account. 

My mail account is an exchange accout with the Chouette add on. 

When I answer a mail and then try to access ThunderAI, then a window open - from the mail composing window. 

Any idea?

**Comment by micz** [comment]
May you try this version? https://github.com/micz/ThunderAI/releases/tag/v2.2.0pre5

**Comment by soufron** [comment]
> May you try this version? https://github.com/micz/ThunderAI/releases/tag/v2.2.0pre5

Tried to. 

I get to select one of 4 choices, but then it put the choice in a small window, and then nothing... 

Have a look

<img width="280" alt="image" src="https://github.com/user-attachments/assets/14afac23-86c4-48f1-a355-0e68461ad239">

It works fine with my other mail accounts though. 

Only my main account behaves like this.

**Comment by soufron** [comment]
> May you try this version? https://github.com/micz/ThunderAI/releases/tag/v2.2.0pre5

Hi, it opens a selection of 4 choices but then I get stuck with a little prompt and that's it... 

Have a look: 

<img width="280" alt="image" src="https://github.com/user-attachments/assets/530fe9dc-4af7-493d-8fec-aedbd552617c">

This only happens on my main account - an exchange account with chouette. 

It works fine on my other accounts, which is even more frustrating. 

PS: I deleted the comment on the thunderbird addon platform

**Comment by micz** [comment]
May you post the log here?
When you have the menu with 1. Classer and press enter what does happen?

**Comment by micz** [comment]
There is no need to provide the last piece of information I requested.
I was able to test the Owl addon, and it appears that the email displayed is not standard, so Thunderbird is not loading the required script.
I am now trying to find a way to get Thunderbird to load the script even when using this addon.

**Comment by soufron** [comment]
Well, let me know when you found the way. I would be glad, and you'll have an issue with anyone having to deal with exchange accounts anyway - which is quite a lot.

**Comment by micz** [comment]
I found that the problem is affecting also other addons.
I reached out to the Owl dev to find a solution, since I found no way to fix this in my side.

**Comment by vlbosch** [comment]
> @vlbosch, from the release notes on the Thunderbird Addons website, I found only that Owl fixed a problem in the new Thunderbird release. Could you point me to where I can find more detailed information about this?
> 
> Regarding ThunderAI, I’m simply using the standard API from the Mail Extensions, the moment Owl fixes the problem everything should work.

I also only have the release notes as they're provided on the website of Thunderbird. I assumed the issue was fixed due to their reference to "blank messages" which broke the internal API. Didn't notice it only applies to the last release... I guess we still have to wait then. Thanks for your quick reply!

"Fixes message content being blank in TB 128.4.3, which broke one of the internal APIs in bug 1924291"

**Comment by choosehappy** [comment]
ThunderAI is pretty awesome, thanks for your efforts. just wanted to check back in on this bug request as its been a year - any chance its been resolved?

**Comment by micz** [comment]
I'm sorry I can not do anything on my side. This bug is affecting all addons that are using content scripts, that is a standard feature of the Thunderbird API.
Maybe you could write to Owl support reporting the issue.

**Comment by choosehappy** [comment]
Thank you - i have just done that and will let you know if i hear anything back

**Comment by knussear** [comment]
I sent a query to owl support as well. Really would be useful if these could work together!

**Comment by choosehappy** [comment]
I just received a message from the owl developer that this has been resolved in the latest version. i just tried it out and it seems to work on my side!

**Comment by micz** [comment]
Thank you for your feedback!
Could you tell me in which Thunderbird version and which Owl version?
Thank you!!

**Comment by choosehappy** [comment]
thunderbird: 140.9.1esr (64-bit)

owl: 1.5.0
