### ISSUE TITLE
Blank menu in Linux Wayland

### ISSUE THREAD

**Issue by pmatos** [micz/ThunderAI#151]
### The problem

When I click on AI, I see a blank window.

[Screencast From 2024-10-09 15-56-25.webm](https://github.com/user-attachments/assets/be655b29-4a27-40db-b7bb-384c9500ddfe)

### Which Operative System are you using?

Linux Wayland

### Which version of Thunderbird are you using?

128.2.0esr

### Which version of ThunderAI has the issue?

2.2.0

### Which integration are you using?

OpenAI ChatGPT API

### Anything in the Thunderbird console logs that might be useful?

```txt
Nothing shows up in the console logs when I press the AI button.
```

### Additional information

Great plugin btw - if it works, it's really useful and awesome that also works with Ollama or LM Studio.

**Comment by pmatos** [comment]
> ### The problem
> When I click on AI, I see a blank window.
> 
>  Screencast.From.2024-10-09.15-56-25.webm 
> ### Which Operative System are you using?
> Linux Wayland
> 
> ### Which version of Thunderbird are you using?
> 128.2.0esr
> 
> ### Which version of ThunderAI has the issue?
> 2.2.0
> 
> ### Which integration are you using?
> OpenAI ChatGPT API
> 
> ### Anything in the Thunderbird console logs that might be useful?
> ```
> Nothing shows up in the console logs when I press the AI button.
> ```
> 
> ### Additional information

Great plugin btw - if it works, it's really useful and awesome that also works with Ollama or LM Studio.

**Comment by micz** [comment]
It seems to be a Thunderbird issue on Wayland. You can find more information here: https://bugzilla.mozilla.org/show_bug.cgi?id=1905622

Until it's fixed, you could use ThunderAI 2.1.5, which has the old static menu and already supports the OpenAI ChatGPT API. That version might lack a few fixes, but as long as ChatGPT isn't sending you broken chunks (which is quite rare), it should work fine.

Alternatively, you can launch the prompts using the corresponding numbers, knowing that they are ordered alphabetically. After opening the prompt (you can use the CTRL+ALT+A shortcut), try pressing 1 and then ENTER, for example.

**Comment by pmatos** [comment]
Nice - thanks for pinpointing the issue and linking it. The suggestion of using the numbers is good for now as it seems to have been fixed upstream, so I should get a fixed thunderbird soon.

**Comment by martinrebane** [comment]
Under _Settings_ - _General_ down there you can open an advanced configuration editor. Type and search for **widget.wayland.use-move-to-rect** and click to change it to **false**. This will bypass the bug and will show menu text for ThunderAI.

**Comment by pmatos** [comment]
> Under _Settings_ - _General_ down there you can open an advanced configuration editor. Type and search for **widget.wayland.use-move-to-rect** and click to change it to **false**. This will bypass the bug and will show menu text for ThunderAI.

Ah - that works! :) Nice. Thanks.

**Comment by ehula** [comment]
> Under _Settings_ - _General_ down there you can open an advanced configuration editor. Type and search for **widget.wayland.use-move-to-rect** and click to change it to **false**. This will bypass the bug and will show menu text for ThunderAI.

This works, but the font looks terrible (very condensed). Is that expected? Is there something that can be done to make the font look better?
