### ISSUE TITLE
Additional data to the prompt

### ISSUE THREAD

**Issue by grumpelt-MeyerEDV** [micz/ThunderAI#153]
I think it would be nice to have the option to provide the AI with the sender's email, the recipient's emails, the subject, and also the body as HTML if it contains code. That would make it easier for the AI to detect whether the email is spam. It could also be implemented with placeholders I read from other feature requests here, e.g. [html_body] or [subject].

**Comment by micz** [comment]
Once #146 has been implemented, I think it should be easy to manage other fields.
Thanks for the suggestion.

**Comment by micz** [comment]
To be added:

- [x] mail_body
- [x] html_body
- [x] mail_subject
- [x] selected_text
- [ ] additional_text
- [ ] junk_score
- [ ] recipients
- [ ] author

**Comment by grumpelt-MeyerEDV** [comment]
It works great, thank you for this practical feature.

**Comment by micz** [comment]
Released in version 2.3.0.
