### ISSUE TITLE
CHATGPT connection window bugs

### ISSUE THREAD

**Issue by Bylka-Red** [micz/ThunderAI#155]
### The problem

Hello, I have a problem that I've encountered before but I managed to get through once.

Since the last update, I had to reconnect my CHATGPT account to the extension, the connection window opens, I click on my email and do next then the window turns gray and nothing works.

Here's what I've already done: 

- I tried to connect with google but it's the same thing.
- I've cleared Thunderbird's cache, but the same error.
- I've tried opening the connection window in the browser and then connecting online, but it doesn't work either.
- I've tried to install earlier versions, but it doesn't work.

As a result, I can't use it anymore. If you can help me, that would be great! 

PS: I'm French, I use the online translation, sorry for the mistakes.

PS2: I've posted a screenshot of the window.

![Screenshot_fvbfvfv14](https://github.com/user-attachments/assets/dfc014db-90e6-47c8-afe2-b98141120833)

### Which Operative System are you using?

Windows 11

### Which version of Thunderbird are you using?

128.3.1esr (32 bits)

### Which version of ThunderAI has the issue?

2.2.0

### Which integration are you using?

ChatGPT Web Interface

**Comment by micz** [comment]
May you check the console log for any error when you get that blank page?
May you list other addons that you are using?
Thank you.

**Comment by Bylka-Red** [comment]
Hello and thank you for your feedback.
I don't know how to check the console log.
And I don't have any other extensions, I've just deleted everything.
Thanks for your help.

**Comment by micz** [comment]
To open the console log press CTRL +SHIFT +J.

**Comment by Bylka-Red** [comment]
Thanks for your help, here's what's wrong with the console: 

tb.account.size_on_disk - Truncating float/double number. 4
tb.account.size_on_disk - Attempted to set the scalar to an incompatible value. 2
tb.account.size_on_disk - Truncating float/double number. 6
tb.account.size_on_disk - Attempted to set the scalar to an incompatible value. 2
tb.account.size_on_disk - Truncating float/double number. 2
tb.account.size_on_disk - Attempted to set the scalar to an incompatible value. 2
initNSMouseEvent() est obsolete. Please use the MouseEvent(). browserPopups.js:112:12
The event « key » is not available for some keyboard layouts : key="a" modifiers="accel,alt" id="" messenger.xhtml
PopupNotifications._onButtonEvent: Button click happened before the security delay: 474.3881999994628ms
L’évènement « key » n’est pas disponible pour certaines dispositions de clavier : key="a" modifiers="accel,alt" id="" messenger.xhtml

**Comment by Bylka-Red** [comment]
and I'd like to point out that on my second computer, I'm experiencing the same problem.

**Comment by micz** [comment]
You can find here version 2.2.0_i155_rev1.

Please follow this steps:
1. Download the file [thunderai-v2.2.0_i155_rev1.zip](https://github.com/user-attachments/files/17346224/thunderai-v2.2.0_i155_rev1.zip)
2. Rename it from *.zip to *.xpi
3. Backup your custom prompts if you have any
4. Install this version

In the options page, for the ChatGPT web interface there is a button that opens ChatGPT in a new tab.

Follow this steps:
1. Press the button to open the tab
2. Login in ChatGPT in the opened tab
3. If everything works, close the tab and use ThunderAI. You should be already logged in.
4. If nothing works, check the log again.

Let me know.
Thank you.

**Comment by Bylka-Red** [comment]
I'll do it right away, thank you. I'll get back to you in a few minutes.

**Comment by Bylka-Red** [comment]
Thanks micz !!!!!!!!!!!!!!!!!!!!!!!! Great, it's working again, and on both computers, thanks again for your help, and I don't know if it was you who created this extension, but it's beautiful, I use it every day, thanks again!!! And good evening to you!

**Comment by micz** [comment]
Thanks for the feedback, I'm happy it worked! 
I'll release version 2.2.1 with this workaround.
I'm closing this issue now.

**Comment by Bylka-Red** [comment]
Merci merci
