### ISSUE TITLE
Ollama API (Local LLM) Update Ollama Model list error.

### ISSUE THREAD

**Issue by giftbox-e** [micz/ThunderAI#159]
### The problem

I am using Ubuntu machine and getting it online with ngrok.
On the Host Address I tried to put all the available addresses:
http://localhost:8080
http://127.0.0.1:8080
http://127.0.0.1:11434
http://<<My online Ngrok URL>>

And when I tried to click "Update Ollama Model list"
This error message pops up: 
"Error trying to fetch Ollama models: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

I hope someone can help me with this.

![image](https://github.com/user-attachments/assets/ffc41cb0-b9ed-4b3a-8aa8-e92f9fa0e9df)

### Which Operative System are you using?

Windows 11

### Which version of Thunderbird are you using?

128.3.1esr (64-bit)

### Which version of ThunderAI has the issue?

2.2.0

### Which integration are you using?

Ollama API

**Comment by micz** [comment]
May you post the console log?
Open it with CRTL+SHIFT+J.
Thank you.

**Comment by giftbox-e** [comment]
This turn up on the console log
![image](https://github.com/user-attachments/assets/c19d1114-eb66-490a-8ed8-1b59144cfbb9)

**Comment by micz** [comment]
If you open in a browser the URL http://127.0.0.1:8080/api/tags  what do you get?

**Comment by giftbox-e** [comment]
I got to my usual login page..
![image](https://github.com/user-attachments/assets/df676c29-0046-4585-a254-c2f916a01e37)

**Comment by micz** [comment]
Have you used the complete URL I posted?
Also with the `/api/tags` part?

This is what I get, a JSON response with the models list:

```
{"models":[{"name":"tinyllama:latest","model":"tinyllama:latest","modified_at":"2024-08-20T16:21:32.525160273Z","size":637700138,"digest":"2644915ede352ea7bdfaff0bfac0be74c719d5d5202acb63a6fb095b52f394a4","details":{"parent_model":"","format":"gguf","family":"llama","families":["llama"],"parameter_size":"1B","quantization_level":"Q4_0"}},{"name":"phi3:latest","model":"phi3:latest","modified_at":"2024-08-20T15:16:47.132108777Z","size":2176178913,"digest":"4f222292793889a9a40a020799cfd28d53f3e01af25d48e06c5e708610fc47e9","details":{"parent_model":"","format":"gguf","family":"phi3","families":["phi3"],"parameter_size":"3.8B","quantization_level":"Q4_0"}}]}
```

**Comment by micz** [comment]
If you're using the Open WebUI API, as described here https://docs.openwebui.com/api/, in ThunderAI you should use the OpenAI Compatible API, setting also the API Key, not the Ollama API.

**Comment by micz** [comment]
Given that you're using Open WebUI, maybe you're impacted by #161.
Please try [version 2.2.2](https://github.com/micz/ThunderAI/releases/tag/v2.2.2).

**Comment by kcrkor** [comment]
Confirmed working with `v2.2.2`.

Url: `http(s)://<host>:<port>/api`
Use V1: Unticked

Thank you @micz

**Comment by giftbox-e** [comment]
Hi, so I tried the 2.2.2 version but it seems i cannot do it...
Is there any settings that I should do outside of the addon?
Tried all, including with http://127.0.0.1:8080/api but still not working.

![image](https://github.com/user-attachments/assets/d98b6d84-9b28-4e49-87ed-9625493486a5)

**Comment by evolts21** [comment]
I think you have to use the OpenAI Comp API, not the Ollama API, since you're using the OpenUI Web and uncheck the v1 option.

**Comment by micz** [comment]
@evolts21 is right. You have to choose the OpenAI Comp API. The one with the purple background.
You have also to uncheck the "Keep the "v1" compatibility" option.

![immagine](https://github.com/user-attachments/assets/4daebd93-5695-45c3-baa3-74d702aeb390)
