### ISSUE TITLE
add option to activate ephemeral chat (temporary chat)

### ISSUE THREAD

**Issue by banaglitch** [micz/ThunderAI#169]
In some case we need privacy or don't want to populate our history of chats in Chatgpt.

It would be great to offer along each prompt the option to make the conversation ephemeral.

in webChatgpt interface, wouldn't adding "?temporary-chat=true" to the url called inside window do the job ?

**Comment by micz** [comment]
You're right, it works.
I'll add an option for this in version 2.3.0.
Thank you.

**Comment by micz** [comment]
I've released [version 2.3.0pre3](https://github.com/micz/ThunderAI/releases/tag/v2.3.0pre3) with #171 and #169.
May you test it?
Thank you!

**Comment by micz** [comment]
Released in version 2.3.0.
