### ISSUE TITLE
Typo in configuration panel : GTP instead of GPT

### ISSUE THREAD

**Issue by banaglitch** [micz/ThunderAI#170]
### The problem

While selecting the connexion type inside currently I have displayed: 
- Interface Web ChatGTP
- API OpenAI ChatGTP
- ...
- ...

The 2 first options should be spelled with GPT.

### Which Operative System are you using?

Windows 10

### Which version of Thunderbird are you using?

128.3.2esr

### Which version of ThunderAI has the issue?

2.2.1

### Which integration are you using?

ChatGPT Web Interface

**Comment by micz** [comment]
Fix to be released in 2.3.0.
