### ISSUE TITLE
Web chatgpt does not use the default "gpt-4o" model but "GPT-4o mini"

### ISSUE THREAD

**Issue by banaglitch** [micz/ThunderAI#171]
### The problem

While using the web chatgpt feature, everything operates as it should but the model used is not gpt-4o but gpt-4o mini.

When using chatgpt in a autonomus and separate web browser, gpt-4o is the default model used, and gpt4o-mini only available after changing the model in the dedicated options of chatgpt app.
I've got a ChatGPT Plus plan.

Maybe forcing url with ?model=gpt-4o would prevent the web window called by ThunderAI to switch the model ?

### Which Operative System are you using?

Windows 10

### Which version of Thunderbird are you using?

128.3.2esr

### Which version of ThunderAI has the issue?

2.2.1

### Which integration are you using?

ChatGPT Web Interface

**Comment by micz** [comment]
I've released [version 2.3.0pre3](https://github.com/micz/ThunderAI/releases/tag/v2.3.0pre3) with #171 and #169.
May you test it?
Thank you!

**Comment by banaglitch** [comment]
It does not work totally. The model appears to be selected at first sight, but chatGPT website automatically switch model to 4o-mini arbitrarly 80% of the times.
It may be something depending on the delay you send info to the app. If you cannot reproduce, is there a way to have more logs ?

**Comment by micz** [comment]
I was able to replicate the problem.
ChatGPT loads the page and then sets the model. If the prompt is sent too early, it doesn't work sometimes.

In version [2.3.0pre4](https://github.com/micz/ThunderAI/releases/tag/v2.3.0pre4) ThunderAI waits for the correct model to be loaded.
Let me know if this works for you.
Thank you!

**Comment by banaglitch** [comment]
Great ! So far everything is OK.
Thank you for your reactivity 🥇

**Comment by micz** [comment]
Released in version 2.3.0.
