### ISSUE TITLE
Move AI Options to Lower Bar for Better Layout

### ISSUE THREAD

**Issue by gitmurawka** [micz/ThunderAI#173]
**Is your feature request related to a problem? Please describe.**
The current options are visually quite far away from the e-mail text.

**Describe the solution you'd like**
Move the options "AI" to the lower bar like in https://addons.thunderbird.net/de/thunderbird/addon/previous-colors/?src=cb-dl-toprated

**Further Enhancement**
Inline text editing like vscode would be next level, but I guess this would be way more complicated.

Great extension, thank you for the development!

**Comment by micz** [comment]
Thank you for your suggestion!
I had overlooked that option and have never used it before.
In version 2.3.0, the icon in the compose window will be moved to the format toolbar.

**Comment by micz** [comment]
> **Further Enhancement**
> Inline text editing like vscode would be next level, but I guess this would be way more complicated.

It would be a great feature, but at the moment, the Thunderbird API does not provide this option. Writing an experiment to achieve this, if possible, would be too time-intensive and would require requesting full access permissions, which users generally dislike.

**Comment by micz** [comment]
Released in version 2.3.0.

**Comment by superunko64** [comment]
When HTML mail is disabled in server settings, “formatting toolbar” is hidden in “compose window” and ThunderAI button is not displayed.

**Comment by kpym** [comment]
I have the same problem as @superunko64. I compose my emails in plain text, so the formatting toolbar is not available, and so neither is theThunderAI button.

**Comment by micz** [comment]
Thank you for the feedback, I filed issue #175 and going to revert this one.
There is no way to conditionally show the button in a different place if the html setting is disabled.

**Comment by micz** [comment]
Version 2.3.1 released: https://github.com/micz/ThunderAI/releases/tag/v2.3.1

**Comment by kpym** [comment]
@micz Thanks for considering the request 🙏
