### ISSUE TITLE
Chatgpt never gets past "work in progress"

### ISSUE THREAD

**Issue by kmand** [micz/ThunderAI#178]
Besides the above if I try "open chatgpt tab" the tab comes u[ but when I type the message there is no response from chatgpt.

I can this  in the debug window

Uncaught (in promise) Error: Unexpected Server Error
[chatgpt.com:21:7](https://chatgpt.com/)
    e https://chatgpt.com/:14
    r https://chatgpt.com/:23
    <anonymous> https://chatgpt.com/:35

I wonder if this has anything to do with my login id on chatgpt which is a different email address than the one thunderbird  is using.

**Comment by micz** [comment]
What version of Thunderbird are you using?
What version of ThunderAI?

**Comment by kmand** [comment]
thunderai-v2.3.2. This broke somewhere around Thunderbird 132.0b5 but is now working in 133.0b3,

**Comment by micz** [comment]
Ok, I'm closing this issue.
