### ISSUE TITLE
Problem with selected model, but nothing is selected

### ISSUE THREAD

**Issue by acescos** [micz/ThunderAI#179]
### The problem

No model was selected, yet an error message indicated a problem loading the selected model.

### Which Operative System are you using?

Fedora Linux 40

### Which version of Thunderbird are you using?

128.3.3esr (64-bit)

### Which version of ThunderAI has the issue?

2.3.1

### Which integration are you using?

ChatGPT Web Interface

### Anything in the Thunderbird console logs that might be useful?

```txt
You have set the option to use a specific model, but it seems that it is not loading correctly. Please check the value and try again. For now, you can press the blue button to continue. Use the current model
```

### Additional information

![imagen](https://github.com/user-attachments/assets/1bc3b2d9-19f6-4f1a-b829-ba1ce8207b02)

**Comment by micz** [comment]
Version 2.3.2 is now available also updating directly from Thunderbird.
