### ISSUE TITLE
Please add the option to add the button/icon to the menu bar

### ISSUE THREAD

**Issue by grossherr** [micz/ThunderAI#180]
Please add the possibility to add the button/icon to the menu bar, so the functionality can be accessed at other places in thunderbird. 

Additionally, I think, access via the right click context menu would further improve the functionality.

This would be outstanding and highly appreciated.

**Comment by micz** [comment]
If you mean the toolbar as in #173 it's not possible due to #175, when composing plain text email the toolbar is hidden and there is no way for an addon to choose where to show the button at runtime.

In the context menu is not possible to use the dynamic menu to search the prompts. The fastest way to open that menu is to use the keyboard shortcut Ctrl+Alt+A.

**Comment by micz** [comment]
You can find more info here: https://micz.it/thunderbird-addon-thunderai/dynamic-menu/

**Comment by grossherr** [comment]
Thank you for the feedback. 

My interest is to use the functionality outside the email editing windows/tab.

**Comment by micz** [comment]
When reading an email the button is here:

![immagine](https://github.com/user-attachments/assets/81f84ea5-36da-412e-8774-0edf314aa06c)

May you show me where you'd like to see it?

**Comment by micz** [comment]
See #182 for calendar events.

**Comment by grossherr** [comment]
I use WhatsApp and Telegram via add-ons. I was just thinking about the having my own instructions/prompts, be it for the messengers or the events. For example, select or copy the last message in chat, and then generate a polite answer or rejection or whatever other ideas I will have. Regarding the events, I was more thinking about summarizing longer notes for the description of the event or building an agenda from a paragraph. #182 definitely also looks interesting, but for me to generate responses for my instructions outside of the email functionality of Thunderbird would already be fantastic.

**Comment by micz** [comment]
Currently, the Extension API does not allow adding buttons in locations other than the ones I am already using.
Integrating with the calendar requires custom code beyond the Extension APIs (referred to as an "Experiment" add-on), as described in #182.

Integrating with other addons could be even more challenging, if not entirely impossible.
However, if the addons use a standard web content tab, I might be able to check.
Could you link the addons you're using here?

**Comment by grossherr** [comment]
Many other extensions have buttons in the area I highlighted—number 1 in the screenshot. All the buttons in my screenshot are from different add-ons. 

The button highlight with number 2 is even from the extension AI Anywhere for ChatGPT. Which is generally is fine, but, for one, I would much prefer to just use one AI extension. Secondly, it doesn't support the temporary chat feature, shich so inconvenient because I don't like my ChatGPT history to be cluttered with the one-off/small requests. 

![2024-11-23_15-40](https://github.com/user-attachments/assets/3c0a2376-62c4-4ffe-9331-9b2cdf079647)
![2024-11-23_15-39](https://github.com/user-attachments/assets/05c6267c-fce3-45e6-9222-5e97a66c30c3)

**Comment by micz** [comment]
Thank you for the video and the info!!

I got the contextual menu idea and filed issue #184. I need to do some additional work to keep the return workflow depending on the source, but it's doable,

Regarding the toolbar menu, the problem is that I don't want to add an AI popup without integration in the context and I don't find any other use.
We already have button in reading and compose window and with #184, we'll have a contextual menu also for generic webpages when some text is selected.
Am I missing something?

**Comment by grossherr** [comment]
My pleasure. I understand the concern of having the additional button up in the toolbar. 

The context menu will be outstanding to have—especially without the need to define everything twice/use two extensions. If it is possible to show the AI context menu when editing an event or a task, that would be an amazing killer feature.

[Screencast from 2024-11-23 23:09:42.webm](https://github.com/user-attachments/assets/eedcc75b-2457-4233-b766-3631088650e5)

Let me just throw this out there too, I feel like an option to have a ChatGPT popup, tab or new window —personally I want a new window, but people might have different needs— open via shortcut would complete the available options. It gives the possibility to utilize ChatGPT for non standardized prompts. Moreover, like in the Telegram chat, it doesn't show the native menu for the context actions everywhere.

**Comment by micz** [comment]
After #182 maybe I could find a way to add the context menu also there. There are no antive ways to do it like in the standard Thunderbird window.

To open the ChatGPT in a new tab I could use a spaces button. What do you think about it?

**Comment by grossherr** [comment]
That could be a good position for the button, but I can't stress enough the importance of the option to open a new window. Why is this so important? Simply because the whole process for this workflow is to have ChatGPT alongside whatever you're working on. Having a tab and then moving it to a new window is cumbersome and introduces unnecessary additional steps. Like I said, I would also love to see the option for a shortcut because of its ease of use.

**Comment by micz** [comment]
I get it.
I filed issue #186.
I'll add it in the companion add-on I'll use to add experimental features (like the Calendar integration).
I'll call it _ThunderAI [Sparks](https://github.com/micz/ThunderAI/issues?q=is%3Aissue+is%3Aopen+label%3ASparks)_.
