### ISSUE TITLE
Using ThunderAI with API does not seem to connect

### ISSUE THREAD

**Issue by crapforge** [micz/ThunderAI#190]
### The problem

Hi,

when using ThunderAI with my newly generated API key the request is generated but then seems to hang without getting a reply from the OpenAI server:

![bugtai](https://github.com/user-attachments/assets/84800dcb-a248-4cd2-b197-f30c3cf7ff67)

(Sorry for using German, but it should be quite clear that nothing is happening here.)

Works fine via Web Interface though. 

I'm using Thunderbird 128.5.1esr (64-Bit) and ThunderAI 2.3.3.

Probably has something to with [https://github.com/micz/ThunderAI/issues/107 ](https://github.com/micz/ThunderAI/issues/107) ?

Thanks for any help!

### Which Operative System are you using?

Windows 10

### Which version of Thunderbird are you using?

128.5.1esr (64-Bit)

### Which version of ThunderAI has the issue?

2.3.3

### Which integration are you using?

OpenAI ChatGPT API

**Comment by micz** [comment]
May you activate the debug option in the add-on preferences, retry and post the log from the console?
Thank you.

**Comment by micz** [comment]
May you activate the debug option in the add-on preferences, retry and post the log from the console?
Thank you.

**Comment by crapforge** [comment]
I have an idea what might be going wrong. This is from the reply section of the console: 

```
XHRPOST
https://api.openai.com/v1/chat/completions
[HTTP/3 429  306ms]

	
error	Object { message: "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.", type: "insufficient_quota", code: "insufficient_quota", … }
message	"You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors."
type	"insufficient_quota"
param	null
code	"insufficient_quota"
```

Yet I have ChatGPT Plus and just created an API key and have not used the API anytime before. 

Any idea what could go wrong here?

**Comment by crapforge** [comment]
I just learned that I have to pay to use the API and that it is not included in ChatGPT Plus.

Nevermind my stupid question here. 

Thanks for your work!

**Comment by micz** [comment]
Yes, you're right, the API needs to be paid for separately from the Plus subscription.

However, ThunderAI should display an error message in this case, and it seems that it's not doing so.
I'll investigate the issue.

Thank you!

**Comment by micz** [comment]
I was able to replicate the problem and filed issue #191.
Thank you.
