### ISSUE TITLE
Ollama API compatability seems to be outdated

### ISSUE THREAD

**Issue by sldkfj39h98h** [micz/ThunderAI#194]
### The problem

I am currently facing an issue with the ThunderAI extension while integrating it with the Ollama API running locally on http://127.0.0.1:11434. It seems that the extension is configured to use the outdated /models endpoint, which has been replaced by /api/tags or other newer API definitions in the latest versions of Ollama. Please check to support the latest api configuration. 

### Which Operative System are you using?

MacOSX

### Which version of Thunderbird are you using?

128.5.1esr 

### Which version of ThunderAI has the issue?

2.3.3

### Which integration are you using?

Ollama API

**Comment by micz** [comment]
What symptoms are you experiencing?
The Ollama API is using the /api/tags since the beginning: https://github.com/micz/ThunderAI/blob/v2.3.4/js/api/ollama.js#L33

**Comment by micz** [comment]
What symptoms are you experiencing?
The Ollama API is using the /api/tags since the beginning: https://github.com/micz/ThunderAI/blob/v2.3.4/js/api/ollama.js#L33
