### ISSUE TITLE
Waiting for the server response...

### ISSUE THREAD

**Issue by wgnmedia** [micz/ThunderAI#195]
### The problem

Using the latest version of the ChatGPT API, every time I try to send a query, I encounter the message: "Waiting for the server response..." and receive no response.

![shot_241211_135726](https://github.com/user-attachments/assets/8ed1b31d-83e1-41db-bd34-e30cad082621)

### Which Operative System are you using?

Windows 10

### Which version of Thunderbird are you using?

128.5.1esr (64-bit)

### Which version of ThunderAI has the issue?

2.3.3

### Which integration are you using?

OpenAI ChatGPT API

**Comment by micz** [comment]
May you activate the debug option in the addon preferences, try again and post here the log?
Thanks.

**Comment by wgnmedia** [comment]
This is the error I'm getting:
'[ThunderAI Logger | model-worker-openai] error_message: "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors."

I do have ChatGPT Plus account and I'm logged in to it.

**Comment by micz** [comment]
I'm sorry, the ChatGPT Plus subscription is not sufficient to use the API. Unfortunately, you need to purchase credits, which will then be deducted based on your API usage.

Additionally, ThunderAI [2.3.4](https://github.com/micz/ThunderAI/releases/tag/v2.3.4) has fixed the issue where this message was not properly displayed on-screen, see #191.
That version is waiting to be reviewed to get published on the Thunderbird website.

**Comment by wgnmedia** [comment]
I would like to confirm that the issue has been resolved and everything is operating as expected.

I regret any inconvenience caused by my earlier lack of awareness.

**Comment by micz** [comment]
Don't worry, the bug in #191 isn't helping with this matter. Thinking that the Plus subscription allows API usage is a common mistake (I made it myself the first time I tried the API).

I'm closing this issue now.
Thank you for the feedback!
