### ISSUE TITLE
Fix ChatGTP-4 support

### ISSUE THREAD

**Issue by micz** [micz/ThunderAI#27]
When a user is working with ChatGPT-4, there may be a slight delay in loading it in the web interface.

The script must wait for ChatGPT-4 to load before injecting the prompt. If the prompt is injected too early, the response could be erased by the ChatGPT-4 reload. This behavior is not consistent.

- [x] Wait for ChatGPT-4 to load before executing the command at [line 163 in mzta-chatgpt.js](https://github.com/micz/ThunderAI/blob/a34470466be24a420ead78990f97ff8c2f51f093/js/mzta-chatgpt.js#L163)
- [x] Add an option to select ChatGPT-4 (default _false_)
- [x] Implement a message in the injected div if there is a timeout while waiting for ChatGPT-4 to load. Instruct the user to select the correct ChatGPT version or to correctly set the related option.

**Comment by kfletche** [comment]
Came here to mention this.. thank you for the great work btw. Love your extension.

**Comment by micz** [comment]
May you try the version _1.0.2pre1_ dowloading the new xpi from [here](https://github.com/micz/ThunderAI/releases/tag/v1.0.2pre1)?
Add your feedback here as a comment.
Thank you!

**Comment by volker78** [comment]
Thank you for the update. Unfortunately, it still switches back to GPT-3.5

**Comment by micz** [comment]
Have you activated the checkbox in the preferences panel?

**Comment by volker78** [comment]
Good point :-)
Works perfectly fine!
Great!

**Comment by micz** [comment]
Fixed in version 1.0.2, currently waiting to be published in the Thunderbird addon site: https://addons.thunderbird.net/it/thunderbird/addon/thunderai/
