### ISSUE TITLE
Use the correct identity when replying

### ISSUE THREAD

**Issue by micz** [micz/ThunderAI#31]
Check if thunderbird is using the correct identity wehn replying to an email if there are more identity present in the profile.

As described here: https://addons.thunderbird.net/it/thunderbird/addon/thunderai/reviews/1173820/

**Comment by micz** [comment]
Found the problem. Extract from the [Official Thunderbird Compose API documentation](https://webextension-api.thunderbird.net/en/115/compose.html):

> Note: If no identity is specified, this function is using the default identity and not the identity of the referenced message.

**Comment by micz** [comment]
The fix will be released in version 1.0.3.

Now ThunderAI looks for an identity email in the author, bcc, cc, recipient fields in the original message.
If nothig is found it uses the first identity present in the profile.

**Comment by umgpy** [comment]
I am facing this issue now, it always seems to be defaulting to another profile rather than to account it was sent to when replying to emails.

Sometimes it keeps the initial reviving account in the 'To' section along with the original sender.

**Comment by umgpy** [comment]
It is happening in all emails all addressed to me, with or without people in cc.

**Comment by micz** [comment]
ThunderAI will search you email address in the from, to and cc fields.

The email address is the one set in the Account Settings, in the field "Email Address":

![Image](https://github.com/user-attachments/assets/a7901b4e-80da-4f0f-a1ff-fccb12e5f5c0)

**Comment by umgpy** [comment]
![Image](https://github.com/user-attachments/assets/a7e26a27-b85a-441f-8f24-ee2827522f37)

In my case, the first account in yellow is used when replying regardless of the receiving account (the other email IDs).

**Comment by micz** [comment]
Maybe the mail addesses are written in capitol letters in the settings page?
