### ISSUE TITLE
Include custom text in any prompt

### ISSUE THREAD

**Issue by micz** [micz/ThunderAI#32]
Add the ability to add custom text to any prompt.
Add an attribute to the prompt that asks the user to write a text to improve the text.

**Comment by twigandolive** [comment]
Perhaps in the drop-down menu there could be "reply" for just a standard reply and a "reply*" (or however) to reply but add prompts and considerations to the reply to feed into the AI?

**Comment by micz** [comment]
The idea is to release this in [version 1.1](https://github.com/micz/ThunderAI/milestone/2) with custom prompts (see #12), allowing every user to customize the behavior of each prompt and add new ones.

**Comment by twigandolive** [comment]
Wonderful - great work! I don't people appreciate (yet) just how much potential you have here integrating TB with ChatGPT like this.

**Comment by micz** [comment]
Will be released in version 1.1.

**Comment by micz** [comment]
This feature can be tested in the new prelease version: https://github.com/micz/ThunderAI/releases/tag/v1.1.0pre1
