### ISSUE TITLE
(bug) only blank ThunderAI window on any action

### ISSUE THREAD

**Issue by zWhdmB5T** [micz/ThunderAI#33]
Dear all,

I just came around your MozTB add-on and wanted to try it.

### issue

- I select an e-mail for further actions.
- I choose one of the supported actions of ThunderAI for this specific e-mail
- a new, just blank, window opens, nothing more

### system details

- openSUSE Leap 15.5 (current update level)
- MozTB 115.10.1 (German)
- [ThunderAI](https://addons.thunderbird.net/en-US/thunderbird/addon/thunderai/) 1.0.2

### other installed add-ons

- [Allow HTML Temp](https://addons.thunderbird.net/en-US/thunderbird/addon/allow-html-temp/) 9.0.0
- [CardBook](https://addons.thunderbird.net/en-US/thunderbird/addon/cardbook/) 93.7
- [DKIM Verifier](https://addons.thunderbird.net/en-US/thunderbird/addon/dkim-verifier/) 5.4.0
- [Mail Merge](https://addons.thunderbird.net/en-US/thunderbird/addon/mail-merge/) 10.4.0
- [No Message Pane Sort](https://addons.thunderbird.net/en-US/thunderbird/addon/no-message-pane-sort-by-mouse/) 3.0.2
- I temporarily disabled the above ones, but no positive effect

### attachments, e.g. screenshot
![Bildschirmfoto_2024-04-29_09-46-10](https://github.com/micz/ThunderAI/assets/143814533/b9dbef80-621a-441a-ac1f-59ccbbd38f35)

**Comment by micz** [comment]
It seems that the ChatGPT webpage is not loading.
Could you please send me the console log?

If it's more convenient, you can email it to me at m@micz.it.
