### ISSUE TITLE
Streamline typed reply

### ISSUE THREAD

**Issue by twigandolive** [micz/ThunderAI#36]
Can it be done where the typed reply can be either typed directly into the email reply or a one-click option from the ChatGPT window to reply to the email in the standard way and have the text directly copied and pasted into the body of the email? 

The latter method would be preferred since modifications can happen directly in the ChatGPT window before finally pasting into the reply. It would automate several steps.

**Comment by micz** [comment]
I think that sending the email directly without reviewing it is too prone to errors, not only in the mail body but possibly also in the recipients' list.

**Comment by twigandolive** [comment]
I'm not talking about sending without reviewing. The opposite, actually. Maybe I wrote it confusingly. And now that I returned to the process, I see the "Use last Reply" button that does exactly as I want. Great job!
