### ISSUE TITLE
ChatGPT 4 won't acknowledge

### ISSUE THREAD

**Issue by twigandolive** [micz/ThunderAI#38]
<img width="1312" alt="Screenshot 2024-05-02 at 3 58 13 PM" src="https://github.com/micz/ThunderAI/assets/59617346/928918ff-10dc-4ccf-9bee-1de0c598448a">

I'm still struggling to get ChatGPT 4 to work. I have it selected in ThunderAI preferences and logged in with a paid account, but I get this error message every time.

**Comment by micz** [comment]
I was able to reproduce the problem and I'm currently analyzing it.
In the meantime, could you test it with a width of 700 for the ChatGPT window dimension?

**Comment by twigandolive** [comment]
I tested with 700x700, and I was able to use ChatGPT 4.

**Comment by twigandolive** [comment]
For the error, my window was set to 1200x1200.

**Comment by micz** [comment]
Thank you for the info. I'll fix it.
[Status page](https://micz.it/thunderdbird-addon-thunderai/status/) updated.

**Comment by micz** [comment]
Fixed in [v1.0.5](https://github.com/micz/ThunderAI/releases/tag/v1.0.5).
