### ISSUE TITLE
Updating to 1.0.5 and "Work in Progress..." icon does not resolve

### ISSUE THREAD

**Issue by twigandolive** [micz/ThunderAI#43]
After updating to 1.0.5, the "Work in Progress..." button remains even after the reply is written. Just as in previous versions, there should be a button to "Use the last message" to automatically insert into a reply. I tried re-installing the extension, restarting TB, and restarting my Mac.

**Comment by micz** [comment]
The problem is not version 1.0.5.
They have changed something in the interface.
I'll check this.

**Comment by micz** [comment]
I'm going to release version 1.0.6 that fixes this problem.
I've added also a way to force che completion in the right bottom corner of the window:

![immagine](https://github.com/micz/ThunderAI/assets/61795/75b93cf7-c2c9-430d-baa1-a06b212d19ef)

**Comment by micz** [comment]
v1.0.6 released.

@twigandolive you can download the thunderai-v1.0.6.xpi directly from here: https://github.com/micz/ThunderAI/releases/tag/v1.0.6
