### ISSUE TITLE
When clicking "Use Last Answer", Signature in removed in reply

### ISSUE THREAD

**Issue by twigandolive** [micz/ThunderAI#45]
After completing a reply, when I click "Use Last Answer", TB generates a reply to the message with my signature at the top. As soon as the message's contents are pasted into the email, the signature is removed. I confirmed this one two mail accounts.

**Comment by micz** [comment]
You're right.
The problem is present only if the signature is above the quoted text.

**Comment by twigandolive** [comment]
I can confirm my signature is above the quoted text. Appreciate your incredible hard work.

**Comment by micz** [comment]
Released in version [1.0.7](https://github.com/micz/ThunderAI/releases/tag/v1.0.7)
