### ISSUE TITLE
Change or add prompts 

### ISSUE THREAD

**Issue by acescos** [micz/ThunderAI#47]
I'm interested in a feature that allows me to adjust or add to prompts, giving me greater flexibility in interactions or tasks. With this capability, I'd be able to customize prompts according to my particular requirements or preferences, elevating the overall experience.

**Comment by micz** [comment]
I'm working on version 1.1, which will include custom prompts, allowing users to personalize their experience, as described in #12.

You can see the details of all the new features here: https://github.com/micz/ThunderAI/milestone/2

I'm closing this issue, you can follow the progress on issue #12.
Thank you

**Comment by micz** [comment]
This feature can be tested in the new pre-release version: https://github.com/micz/ThunderAI/releases/tag/v1.1.0pre1
