### ISSUE TITLE
changing prompts

### ISSUE THREAD

**Issue by Whynightman** [micz/ThunderAI#73]
For me the action of changing prompts (the buttons) are greyed out. adding new ones isn't an issue though!.

screenshot is added
![Screenshot 2024-06-21 235920](https://github.com/micz/ThunderAI/assets/63508208/6650c78d-5f2f-4537-8262-a296e632ce5b)

**Comment by Whynightman** [comment]
other than that, this is an absolutely lovely add-on btw :). thanks mate

**Comment by micz** [comment]
That's correct. Those are the default prompts, they can't be modified. 
If you don't want to use one of them, you can disable it and add a new one copying and pasting the original prompt.
Maybe I should write it somewhere on the custom prompts page. 
Thank you!

**Comment by micz** [comment]
I'm closing this issue. Feel free to reopen it if you need more info.
