### ISSUE TITLE
ChatGPT-4o

### ISSUE THREAD

**Issue by Weboutgr** [micz/ThunderAI#75]
hello

I get this message:

You have set the option to use ChatGPT-4, but it seems that it is not loading correctly. Have you chosen the right model at the top?

When i choose the  4o then works fine

**Comment by micz** [comment]
Setting the model in the options and waiting for the user to change it the first time is the only way to enable the use of models 4 or 4o.
As described in #76, I will also include model 4o in the warning text for added clarity.
Thank you!
