### ISSUE TITLE
I can't seem to log in to ChatGPT no matter what I do

### ISSUE THREAD

**Issue by Mikilio** [micz/ThunderAI#90]
The only time I ever managed to enter the log in screen was when I clicked on the link while analyzing the traffic on debug mode. I did not stay logged in, however. How is this supposed to work?

**Comment by Mikilio** [comment]
Here are the console logs:
```
[ThunderAI] Prompt length: 1563 mzta-background.js:143:13
Content-Security-Policy: Couldn’t process unknown directive ‘report-to’ login
Some cookies are misusing the recommended “SameSite“ attribute 2
Ignoring unsupported entryTypes: largest-contentful-paint. _app-8de771af4ef908a0.js:38:624894
Ignoring unsupported entryTypes: layout-shift. _app-8de771af4ef908a0.js:38:624894
Ignoring unsupported entryTypes: longtask. _app-8de771af4ef908a0.js:38:625054
Source map error: Error: request failed with status 404
Resource URL: https://cdn.oaistatic.com/_next/static/chunks/pages/_app-8de771af4ef908a0.js
Source Map URL: _app-8de771af4ef908a0.js.map
WebExtensions: Window manager refused to set window to state 3. ext-mail.js:1699
[ThunderAI] Script started... mzta-background.js:156:13
[ThunderAI] Script injected successfully mzta-background.js:189:21
```

**Comment by Mikilio** [comment]
I guess my window manager doesn't want to let the popup resize, because it wants to tile it. While I can work around this, I believe the popup just display in the size my window manager wants it to display and not complain.

**Comment by Mikilio** [comment]
I can confirm that it won't work even if I float the window.

**Comment by micz** [comment]
May you tell me the Thunderbird version and which operative System are you using?

**Comment by micz** [comment]
> The only time I ever managed to enter the log in screen was when I clicked on the link while analyzing the traffic on debug mode. I did not stay logged in, however. How is this supposed to work?

The first time you use the add-on, it will prompt you to log in to ChatGPT. After logging in, close the window and select the same prompt from the menu again. When the ChatGPT window opens, you should be logged in, and everything should work properly.

In the past, a user experienced a problem related to the strict configuration of Thunderbird, which didn't allow cookies and scripts.

**Comment by Mikilio** [comment]
> In the past, a user experienced a problem related to the strict configuration of Thunderbird, which didn't allow cookies and scripts.

This sounds like it may be happening. I'll get back to you providing more information.

**Comment by Mikilio** [comment]
So I am using NixOS and the configuration I'm using does only configure the `profiles.ini` file and a `user.js` file. Only the user.js file is relevant here, I believe. Could you let me know if anything here seems problematic?
```js
// Generated by Home Manager.

user_pref("mail.account.account_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.identities", "id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8");
user_pref("mail.account.account_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.server", "server_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8");
user_pref("mail.accountmanager.accounts", "account_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8");
user_pref("mail.accountmanager.defaultaccount", "account_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8");
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.attachPgpKey", false);
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.autoEncryptDrafts", true);
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.e2etechpref", 0);
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.encryptionpolicy", 0);
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.fullName", "Kilian Mio");
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.htmlSigText", "");
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.is_gnupg_key_id", true);
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.last_entered_external_gnupg_key_id", "FFF94A5986542148");
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.openpgp_key_id", "FFF94A5986542148");
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.protectSubject", true);
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.sign_mail", true);
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.smtpServer", "smtp_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8");
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.useremail", "official.mikilio@gmail.com");
user_pref("mail.identity.id_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.valid", true);
user_pref("mail.openpgp.allow_external_gnupg", true);
user_pref("mail.server.server_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.directory", ".thunderbird/default/ImapMail/ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8");
user_pref("mail.server.server_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.directory-rel", "[ProfD]ImapMail/ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8");
user_pref("mail.server.server_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.hostname", "imap.gmail.com");
user_pref("mail.server.server_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.login_at_startup", true);
user_pref("mail.server.server_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.name", "Google");
user_pref("mail.server.server_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.port", 993);
user_pref("mail.server.server_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.socketType", 3);
user_pref("mail.server.server_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.type", "imap");
user_pref("mail.server.server_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.userName", "official.mikilio@gmail.com");
user_pref("mail.smtp.defaultserver", "smtp_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8");
user_pref("mail.smtpserver.smtp_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.authMethod", 10);
user_pref("mail.smtpserver.smtp_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.hostname", "smtp.gmail.com");
user_pref("mail.smtpserver.smtp_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.port", 465);
user_pref("mail.smtpserver.smtp_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.try_ssl", 3);
user_pref("mail.smtpserver.smtp_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8.username", "official.mikilio@gmail.com");
user_pref("mail.smtpservers", "smtp_ce770667e5f9b0d8f55367bb79419689d90c48451bb33f079f3a9a72ae132de8");
```
If you suspect that the problem is with the thunderbird package in nixpkgs then I'll make an issue there.

**Comment by micz** [comment]
I always get a lot of error from the chatgpt page, even if it works.

I see nothing in your configuration that could give the error you're reporting. I'm sorry I do not know NixOS, I'm downloading the VirtualBOx version to try it.

I suggest you delete the configuration you posted, because there is your email visible.

**Comment by micz** [comment]
I donwloaded this NixOS version: https://nixos.org/download/#nixos-virtualbox
Installed thunderbird 115.12.2 from terminal with `nix-shell - p thunderbird`, installed ThunderAI and evertything worked.

**Comment by Mikilio** [comment]
> I suggest you delete the configuration you posted, because there is your email visible.

Thank you for the warning, however, everything there is public information.

I guess I will try to debug myself then because it must have something to do with my environment.

**Comment by Mikilio** [comment]
So I found the spot that closes the browser popup before I can interact with it.
It's in chrome://messenger/content/parent/ext-mail.js line 1661
The browser popup seems to have "maximized" initial `window.windowState` but it should be "normal" state. It tried to do some operations to achieve that of which all fail until it ultimately runs:
```js
window.sizeToContent();
```
After which, the browser window disappears without showing any error on the console.
How do we proceed?

**Comment by micz** [comment]
This should be the line you found: https://github.com/mozilla/releases-comm-central/blob/2e0cd2b03bea7839120f79db06476733e964e5ae/mail/components/extensions/parent/ext-mail.js#L1661

`sizeToContent` is used everywhere https://github.com/search?q=repo%3Amozilla%2Freleases-comm-central%20sizeToContent&type=code so I don't think it's a problem.

Are you using KDE in your PC?

**Comment by Mikilio** [comment]
No, I am using Hyprland you suggest I make the issue there?

**Comment by micz** [comment]
You're right, that was not the correct file version, given the line numbers.

I found this: https://www.reddit.com/r/hyprland/comments/1561zkn/how_to_handle_window_popups/

Maybe it could help. Searching for Hyprland and Thunderbird, there are many results.

**Comment by Mikilio** [comment]
Thank you so much, for going as far as to look for workarounds for me. Unfortunately, I've already tried these types of workarounds, as I have stated above. I will take this issue to the Hyprland devs first. Because the problem is already far removed from this extension.

**Comment by micz** [comment]
Ok, no prob.
I'm closing this issue now.
If you need something else, fell free to reopen it.

**Comment by YourSandwich** [comment]
Hi @Mikilio, have you found a solution? I am having the same issue on ArchLinux with Hyprland

**Comment by YourSandwich** [comment]
I was able to see the window using this rules:
```
windowrulev2 = noinitialfocus, class:^(thunderbird)$
windowrulev2 = float, class:^(thunderbird)$
```

But as soon as i hover over the window it disaperas. its probably something wayland/hyprland specific.
None of the fixes work fully: https://wiki.hyprland.org/FAQ/#some-of-my-drop-downpop-up-windows-in-apps-disappeardont-open-at-cursor-position

**Comment by YourSandwich** [comment]
I was able to fix the issue by setting the dimensions to 0

![Image](https://github.com/user-attachments/assets/1c5af232-c8b9-4e8b-80d1-c3b367104a8c)

**Comment by micz** [comment]
@YourSandwich The possiblity to set the dimensions to zero was added in 2.2.0 to solve this issue. So that is the right way to do it with hyprland. 

You can check the release notes [here](https://github.com/micz/ThunderAI/blob/dc67af1fe68d961dcde5a810e9e205cd6ce570f9/CHANGELOG.md#version-220---07102024).
